# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(338, 292)
        Widget.setStyleSheet("QWidget{\n"
"background-color: \"#defcff\"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:\"green\"\n"
"}\n"
"\n"
"QLabel{\n"
"color:\"red\"\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(110, 60, 100, 30))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.btn_clicked)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(40, 140, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def btn_clicked(self):
        self.label.setText("PLEASE WORK")
        self.label.setStyleSheet('background-color:yellow')

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.pushButton.setText(_translate("Widget", "Click Me"))
        self.label.setText(_translate("Widget", "TextLabel"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Widget = QtWidgets.QWidget()
#     ui = Ui_Widget()
#     ui.setupUi(Widget)
#     Widget.show()
#     sys.exit(app.exec_())
